### ISSUE TITLE
Zellij runner doesn't update on change directory screen

### ISSUE THREAD

**Issue by praveenperera** [alex35mil/dotfiles#3]
Hey great dotfiles by the way, using it to switch from tmux to zellij.

When I run zellij runner, sometimes the UI doesn't update on the change directory screen and I have to quit the terminal. This happens every time I say yes on the "change directory" screen. The screen does not change and and everything appears to get stuck.

I'll update this issue with more info or a PR if I figure it out. Thought you might have an idea on what's happening.

**Comment by tlvenn** [comment]
Just discovered the runner and running into the same issue on OSX if that matters.

**Comment by praveenperera** [comment]
I’m also on MacOS

**Comment by alex35mil** [comment]
@praveenperera @tlvenn 

Hey, the directory chooser is hella non-optimized, and _I think_ there might be issues when there are a lot of directories in the search scope. 

Have you tried to narrow the search scope by setting env vars described [here](https://github.com/alex35mil/dotfiles/tree/master/user/bin/zellij/runner#paths-autocompletion)?

**Comment by praveenperera** [comment]
@alex35mil yup that's definitely, the issue. I let it run just took a while.

**Comment by alex35mil** [comment]
Yeah, it would need async to optimize dir picker, but I didn't get around to exploring how it would play with tui lib.

**Comment by praveenperera** [comment]
@alex35mil maybe incorporating [Skim](https://crates.io/crates/skim) would the faster and easier option. 

I haven't tried it but i’m assuming it would give you progress indication so people wouldn’t think it’s frozen.

**Comment by alex35mil** [comment]
@praveenperera I considered it for the first version of the runner, but it didn't work out for some reason. I don't remember why. For the current version, I was just lazy and did a primitive search with `ignore` (used in `ripgrep`). Makes sense to try out Skim with the current version of the runner as UI is much more low-level and allows pretty much everything if it is not async.
