### ISSUE TITLE
zellij-runner - Switch session if already inside zellij

### ISSUE THREAD

**Issue by eirabben** [alex35mil/dotfiles#4]
Hi

Right now, if I run the zellij-runner inside a zellij session, it opens a nested session.

Is there any way to detect whether we are already inside zellij, and switch sessions instead of nesting?

**Comment by alex35mil** [comment]
Hi @eirabben, I'm not sure regarding nesting detection—I don't think it is possible off the top of my head, but maybe I'm wrong, and Zellij exposes some handle. And it is 100% impossible to switch instead of to nest without a manager process running somewhere.

**Comment by eirabben** [comment]
Ok, thank you for your quick reply.

Seems like this kind of functionality would have to be handled inside zellij directly.

Thank you for your time!

**Comment by alex35mil** [comment]
Yup, exactly.
