### ISSUE TITLE
ANSI output is garbled, need to run list-sessions with -n

### ISSUE THREAD

**Issue by robrecord** [alex35mil/dotfiles#6]
https://github.com/alex35mil/dotfiles/blob/483f7ad7c69a9ef0f24468d11b4aca4db0d0f75d/bin/zellij/runner/src/zellij.rs#L11C54-L11C54

New versions of zellij come with colourized output of list-sessions by default, which appeared messed up in zellij-runner's list of sessions. Additionally extra session information is added to the end of each item.

Consequently the session attach does not work.

~~A workaround would be to add `-n` to the `list-sessions` command, and then separate the session information from the session name.~~

EDIT: a new flag, `-s` or `--short`, has been [added to the `list-sessions` command](https://github.com/zellij-org/zellij/pull/2857) to output session names pristinely for easy parsing.

**Comment by robrecord** [comment]
<img width="533" alt="Screenshot 2023-10-13 at 16 53 01" src="https://github.com/alex35mil/dotfiles/assets/38916/dc6b96b3-1e16-46a3-8ea3-e5fae2ca641c">

**Comment by robrecord** [comment]
<img width="505" alt="Screenshot 2023-10-13 at 16 54 18" src="https://github.com/alex35mil/dotfiles/assets/38916/49cf5aef-e3e3-49eb-a822-ede02b2b9486">

**Comment by alex35mil** [comment]
@robrecord Which version of zellij are you on? I'm on `0.38.2` (I think it's latest) and I don't see this issue.

**Comment by robrecord** [comment]
Ah, my bad - I’m on a pre-release 0.39 compiled from the main branch… not sure how you’d make it compatible with both versions; might need a version check. I realise that’s possibly awkward.

**Comment by robrecord** [comment]
In light of this not being released yet, perhaps we should wait until the functionality is settled as it could be subject to change.

**Comment by noirbizarre** [comment]
Zellij 0.39 being released, this issue is now existing with latest releases. 
Is it possible to fix it ?
(BTW, your launcher is great and would gain to have a dedicated repository)

**Comment by alex35mil** [comment]
@robrecord @noirbizarre sorry for the delay. Too much on my plate right now. I will update it as soon as I have time. Can't break my workflow when I'm in the middle of the project.

**Comment by alex35mil** [comment]
Should be fixed in `0.4.0`. It would be cool to add a keymap to delete `EXITED` sessions from the main screen, but I don't have a bandwidth for it right now.
