### ISSUE TITLE
zsh-autosuggestions

### ISSUE THREAD

**Issue by poborin** [alex35mil/dotfiles#8]
thanks a lot for this repo!

I just try to get the zsh-autosuggestions  working and wondering where do you get this config from:
```
source "$DEVBOX_PROFILE/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
```
after installing dotfiles I cannot figure out where do I get `~/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/` from. It seems that this folder just don't exist.

**Comment by alex35mil** [comment]
I manage packages with Nix + [Devbox](https://github.com/jetpack-io/devbox), so you need to install it first.

**Comment by poborin** [comment]
Sorry for my ambiguous question. I wanted to ask if I really need a virtual environment to use zsh-autosuggestions.

**Comment by alex35mil** [comment]
@poborin No, absolutely not. You can install them without Nix. If you use Brew, you can get them from [here](https://formulae.brew.sh/formula/zsh-autosuggestions).

**Comment by poborin** [comment]
thanks
